from polyglot.detect import Detector
from polyglot.text import Text

''' Output Language'''
def nameOf(tagname) :
    lang = dict()
    lang['Haitian'] = 'ht'
    lang['Tamil'] = 'ta'
    lang['Vietnamese'] = 'vi'
    lang['Telugu'] = 'te'
    lang['Croatian'] = 'hr'
    lang['Hungarian'] = 'hu'
    lang['Thai'] = 'th'
    lang['Kannada'] = 'kn'
    lang['Tagalog'] = 'tl'
    lang['Armenian'] = 'hy'
    lang['Hebrew(modern)'] = 'he'
    lang['Turkish'] = 'tr'
    lang['Portuguese'] = 'pt'
    lang['Belarusian'] = 'be'
    lang['Norwegian'] = 'nn'
    lang['Dutch'] = 'nl'
    lang['Japanese'] = 'jv'
    lang['Albanian'] = 'sq'
    lang['Bulgarian'] = 'bg'
    lang['Serbian'] = 'sr'
    lang['Swahili'] = 'sw'
    lang['Swedish'] = 'sv'
    lang['French'] = 'fr'
    lang['Latin'] = 'la'
    lang['Czech'] = 'cs'
    lang['Yiddish'] = 'yi'
    lang['Hindi'] = 'hi'
    lang['Danish'] = 'da'
    lang['Finnish'] = 'fi'
    lang['German'] = 'de'
    lang['Slovak'] = 'sk'
    lang['Persian'] = 'lt'
    lang['Lithuanian'] = 'fa'
    lang['Slovene'] = 'sl'
    lang['Latvian'] = 'lv'
    lang['Bosnian'] = 'bs'
    lang['Gujarati'] = 'gu'
    lang['Italian'] = 'it'
    lang['Icelandic'] = 'is'
    lang['Spanish'] = 'es'
    lang['Ukrainian'] = 'uk'
    lang['Georgian'] = 'ka'
    lang['Urdu'] = 'ur'
    lang['Indonesian'] = 'id'
    lang['Marathi'] = 'mr'
    lang['Korean'] = 'ko'
    lang['Galician'] = 'gl'
    lang['Khmer'] = 'km'
    lang['Catalan'] = 'ca'
    lang['Romanian'] = 'ro'
    lang['Basque'] = 'eu'
    lang['Macedonian'] = 'mk'
    lang['Russian'] = 'ru'
    lang['Azerbaijani'] = 'az'
    lang['Chinese'] = 'zh'
    lang['Estonian'] = 'et'
    lang['Welsh'] = 'cy'
    lang['Arabic'] = 'ar'
    lang['Bengali'] = 'bn'
    lang['Amharic'] = 'am'
    lang['Irish'] = 'ga'
    lang['Malay'] = 'ms'
    lang['Polish'] = 'pl'
    lang['Greek'] = 'el'
    lang['Esperanto'] = 'eo'
    lang['Maltese'] = 'mt'
    lang['English'] = 'en'
    for k, v in lang.items() :
        if tagname == v :
            return k
        
def tagOf(language) :
    lang = dict()
    lang['Haitian'] = 'ht'
    lang['Tamil'] = 'ta'
    lang['Vietnamese'] = 'vi'
    lang['Telugu'] = 'te'
    lang['Croatian'] = 'hr'
    lang['Hungarian'] = 'hu'
    lang['Thai'] = 'th'
    lang['Kannada'] = 'kn'
    lang['Tagalog'] = 'tl'
    lang['Armenian'] = 'hy'
    lang['Hebrew(modern)'] = 'he'
    lang['Turkish'] = 'tr'
    lang['Portuguese'] = 'pt'
    lang['Belarusian'] = 'be'
    lang['Norwegian'] = 'nn'
    lang['Dutch'] = 'nl'
    lang['Japanese'] = 'jv'
    lang['Albanian'] = 'sq'
    lang['Bulgarian'] = 'bg'
    lang['Serbian'] = 'sr'
    lang['Swahili'] = 'sw'
    lang['Swedish'] = 'sv'
    lang['French'] = 'fr'
    lang['Latin'] = 'la'
    lang['Czech'] = 'cs'
    lang['Yiddish'] = 'yi'
    lang['Hindi'] = 'hi'
    lang['Danish'] = 'da'
    lang['Finnish'] = 'fi'
    lang['German'] = 'de'
    lang['Slovak'] = 'sk'
    lang['Persian'] = 'lt'
    lang['Lithuanian'] = 'fa'
    lang['Slovene'] = 'sl'
    lang['Latvian'] = 'lv'
    lang['Bosnian'] = 'bs'
    lang['Gujarati'] = 'gu'
    lang['Italian'] = 'it'
    lang['Icelandic'] = 'is'
    lang['Spanish'] = 'es'
    lang['Ukrainian'] = 'uk'
    lang['Georgian'] = 'ka'
    lang['Urdu'] = 'ur'
    lang['Indonesian'] = 'id'
    lang['Marathi'] = 'mr'
    lang['Korean'] = 'ko'
    lang['Galician'] = 'gl'
    lang['Khmer'] = 'km'
    lang['Catalan'] = 'ca'
    lang['Romanian'] = 'ro'
    lang['Basque'] = 'eu'
    lang['Macedonian'] = 'mk'
    lang['Russian'] = 'ru'
    lang['Azerbaijani'] = 'az'
    lang['Chinese'] = 'zh'
    lang['Estonian'] = 'et'
    lang['Welsh'] = 'cy'
    lang['Arabic'] = 'ar'
    lang['Bengali'] = 'bn'
    lang['Amharic'] = 'am'
    lang['Irish'] = 'ga'
    lang['Malay'] = 'ms'
    lang['Polish'] = 'pl'
    lang['Greek'] = 'el'
    lang['Esperanto'] = 'eo'
    lang['Maltese'] = 'mt'
    lang['English'] = 'en'
    ling = language.capitalize()
    for k, v in lang.items() :
        if language == k or ling == k :
            return v

''' This Function Detect the Language of text '''

def detectLang(input_text):
    detector = Detector(input_text)
    lang = detector.language
    return lang

''' This function transliterate the given text into given output language'''

def _transliterate_(_text_, out_lang):
    data = Text(_text_)
    code = tagOf(out_lang)
    outputtext = data.transliterate(code)
    return outputtext
